[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="day01_01"
path="bin/day01/solution_1.rs"

[[bin]]
name="day01_02"
path="bin/day01/solution_2.rs"